name:    hm-demo
version: "0.0.0"

dependencies:
- base >=4.9.1.0 && <5
- containers
#profiling: True

executables:
  Demo:
    source-dirs: app
    # modules: Main
    main: Main
    dependencies: hm-demo
    #ghc-options: -rtsopts

library:
  source-dirs: lib
  # modules: Parsetree,Typedtree,Scheme, Inferencer
  # exposed-modules:
  #   - Data.MyPkg
  ghc-options: -fwarn-name-shadowing
  dependencies:
    - strict-base >=0.4.0.0


# Test suite
tests:
  test1:
    main: BasicSumTest.hs
    source-dirs: tests
    ghc-options: -Wall
    dependencies:
    - hm-demo
    - HUnit
    - hspec >=2.0.0
    - strict-base >=0.4.0.0
